def faulty_method():
    raise ValueError("Custom Exception Raised")

faulty_method()
